name: release

on:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all

jobs:
  release-reusable:
    uses: anyproto/shared-actions/.github/workflows/release-go-daemons-reusable.yml@OPS-835
    secrets: inherit # pass all secrets
